### ISSUE TITLE
GH Writer still doesn't load properly in some cases

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/github-writer#357]
### Details

There are reports that despite the improvements provided in #348[,](https://github.com/ckeditor/github-writer/pull/348,) sometimes GH Writer still doesn't load properly. Let's gather those cases in this issue, then we'll be able to work out the reproduction steps and extract the particular issues.

For each case of the unsuccessful Writer load, please provide:

*   URL where it failed;
*   The context where the editor wasn't loaded (e.g. "Review comment", "New issue comment", "Wiki page" etc) and, if possible, a screenshot (for 2FA :wink:);
*   Information if Writer loaded after the page refresh;
*   Optionally - the markup that failed to load (we haven't noticed any correlation between content and loading yet, but maybe this direction is worth checking).

**Comment by mmotyczynska** [comment]
It happened to me when creating a PR from the button that appears right after pushing a new branch.

The editor loaded after refresh.

Other details can be read from the screenshot.

![](https://user-images.githubusercontent.com/95343030/186418836-52d41054-a16e-4d2d-8daa-0c9cf68db136.png)

**Comment by oleq** [comment]
Editing this comment does not enable GHW https://github.com/cksource/collaboration-features/issues/4719#issuecomment-1227072174

**Comment by Dumluregn** [comment]
> Editing this comment does not enable GHW [cksource/collaboration-features#4719 (comment)](https://github.com/cksource/collaboration-features/issues/4719#issuecomment-1227072174)

WFM in the first try :thinking: 

![](https://user-images.githubusercontent.com/10883184/186648183-72d22a99-6711-4804-bbbd-d520980cdf4b.png)

**Comment by mmotyczynska** [comment]
Another example: creating an issue (bug) using the standard `New Issue` button and then choosing the bug with `Get started` button:  
 

![](https://user-images.githubusercontent.com/95343030/186649080-51bc97e5-ba80-46f7-bd5f-eb26523ea2ea.png)

![](https://user-images.githubusercontent.com/95343030/186649475-b9f14b5f-983e-46cd-b8cb-bcf113d44a66.png)

Refreshing the page helped to load GH Writer, but then I was not able to add a video from my desktop using d&d and had to switch back to the default editor.

![](https://user-images.githubusercontent.com/95343030/186649215-ec0e4ce9-0842-4842-9eed-aa27ca439e58.png)

**Comment by oleq** [comment]
> WFM in the first try 🤔

WFM in the second try

![](https://user-images.githubusercontent.com/1099479/186694799-12398035-0900-4806-8ef3-f1c961d166cf.gif)

**Comment by bdub** [comment]
does not work for me (not working as i write this comment), Firefox or Chrome, on M1 Mac.

**Comment by mateuszzagorski** [comment]
Copied over from: #358.  
  
:memo: Provide detailed reproduction steps (if any)  
GitHub Writer Plug in installed and active  
Go to: [https://github.com/ckeditor/github-writer/issues/new?assignees=&labels=bug&template=1-bug-report.md&title=](https://github.com/ckeditor/github-writer/issues/new?assignees=&labels=bug&template=1-bug-report.md&title=)

:heavy\_check\_mark: Expected result  
Should be able to use the github-writer plug-in edit the Issue

:x: Actual result  
github-writer does not load, and the Edit field is as default.  
Note: console reports the following errors:

```
Possibly unhandled Error: auth:error:not_authed
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:1:86299
    at s (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:60060)
    at N._callHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:29251)
    at N._settlePromiseFromHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:29392)
    at N._settlePromiseAt (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:31646)
    at N._settlePromises (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:33865)
    at N._rejectPromises (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:33734)
    at c._consumeFunctionBuffer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:1213)
    at consumeFunctionBuffer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:666)
    at MutationObserver.<anonymous> (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:51984)
    
Assertion failed: Input argument is not an HTMLInputElement
getFormProfile @ onloadwff.js:71
setFieldValue @ onloadwff.js:71
formKeydownListener @ onloadwff.js:71
```

:page\_with\_curl: Other details  
Browser: … Chrome Version 105.0.5195.52 (Official Build) (arm64)  
OS: …12.5 (21G72)

**UPDATE**: I was able to get the plugin to load. after creating is the comment (and saving it), I then when i went back and tried to edit comment. The Plugin loaded on comment

**Comment by jhgarrison** [comment]
New user here, 1.10.1 on Firefox 109.0.1

Opening any wiki page (or even this comment #357) just displays the standard GitHub text editor.  

It's not completely clear from the docs if one has to do anything special to activate the plugin. Firefox says "Can always read and change data on this site"

**Comment by jhgarrison** [comment]
In the Firefox console I see this:

Error: GitHub Writer error: ("markdown") not found. This page doesn't seem to be compatible with this application anymore. Upgrade to the latest version of the browser extension.
    l util.js:121
    c util.js:98
    c util.js:95
    c util.js:102
    c util.js:95
    yk editor.js:65
    <anonymous> wikieditor.js:8
    createEditor createeditormixin.js:77
    run wikieditor.js:65
    run router.js:113
    run app.js:27
    promise callback*run app.js:26
    <anonymous> github-writer.js:24
    Webpack 3
        i
        <anonymous>
        <anonymous>
[github-writer.js:33:12](webpack:///src/github-writer.js)

Screenshot of editor page attached
![ghwriter01](https://user-images.githubusercontent.com/2840152/217347677-76f50c83-bd03-42d3-bc83-df1d6bbd994d.png)

**Comment by jhgarrison** [comment]
I am by no means knowledgeable in Javascript and writing plugins, but the attached two screenshots are interesting.  I set a breakpoint in the `Editor` constructor. At this point, `this.dom` has a valid value.  

![ghwriter02](https://user-images.githubusercontent.com/2840152/217350201-9b68c970-c34b-48c4-86ee-5ec220d050e3.png)

It is passed to `checkDom` where it appears to be undefined.  

![ghwriter03](https://user-images.githubusercontent.com/2840152/217350219-248f9e6a-e977-47bd-8216-9d8ec32dfd5f.png)

As a long-time Java developer, this looks so wrong it points to a problem with the JS infrastructure itself -- but then I'm not a JS developer.  Is it possible for a parameter value to become undefined in this way?

**Comment by Dumluregn** [comment]
Hello, for everyone reporting an issue with GH Writer loading - please also include a list of browser extensions that are also working on GH interface (like adding extra buttons), e.g. Refined GitHub or Zenhub.

For me, it's Zenhub.
