### ISSUE TITLE
github-writer does not load in Chrome (M1 mac)

### ISSUE THREAD

**Issue by bdub** [ckeditor/github-writer#358]
📝 Provide detailed reproduction steps (if any)

GitHub Writer Plug in installed and active

Go to:

https://github.com/ckeditor/github-writer/issues/new?assignees=&labels=bug&template=1-bug-report.md&title=

✔️ Expected result

Should be able to use the github-writer plug-in edit the Issue  
  
❌ Actual result

github-writer does not load, and the Edit field is as default.

Note:

console reports the following errors:

```
Possibly unhandled Error: auth:error:not_authed
    at chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:1:86299
    at s (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:60060)
    at N._callHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:29251)
    at N._settlePromiseFromHandler (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:29392)
    at N._settlePromiseAt (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:31646)
    at N._settlePromises (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:33865)
    at N._rejectPromises (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:33734)
    at c._consumeFunctionBuffer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:1213)
    at consumeFunctionBuffer (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:666)
    at MutationObserver.<anonymous> (chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/vendor.js:2:51984)
    
Assertion failed: Input argument is not an HTMLInputElement
getFormProfile @ onloadwff.js:71
setFieldValue @ onloadwff.js:71
formKeydownListener @ onloadwff.js:71
```

📃 Other details

Browser: … Chrome Version 105.0.5195.52 (Official Build) (arm64)  
OS: …12.5 (21G72)  
  
UPDATE: I was able to get the plugin to load. after creating is the comment (and saving it), I then when i went back and tried to edit comment. The Plugin loaded on comment

**Comment by mateuszzagorski** [comment]
We've created an issue to aggregate all the scenarios where GitHub Writer does not load correctly -> #357.  
I took the liberty of copying your comment there.
